<?php

/**
 * @file
 * Contains facetapi.module
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityManagerInterface;
use Drupal\search_api\Entity\Index;
use Drupal\search_api\Query\QueryInterface;
use Drupal\facetapi\Entity\Facet;
use Drupal\facetapi\FacetInterface;
use Drupal\Component\Plugin\PluginBase;

/**
 * Implements hook_help().
 */

function facetapi_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the facetapi module.
    case 'help.page.facetapi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Facetapi test') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function facetapi_theme()
{
  $theme = [];

  return $theme;
}


/**
 * Get all facet definitions.
 *
 * @return FacetInterface[]
 */
function facetapi_get_enabled_facets() {
  $module_handler = \Drupal::service('module_handler');
  $facets = $module_handler->invokeAll('facetapi_facet_info');
  return $facets;
}

/**
 * Implements hook_entity_type_build().
 */
function facetapi_entity_type_build(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['search_api_index']
    ->setFormClass('facets', 'Drupal\facetapi\Form\IndexFacetsForm');
}


/**
 * Implementation of hook_search_api_query_alter.
 *
 * @param \Drupal\search_api\Query\QueryInterface $query
 */
function facetapi_search_api_query_alter(QueryInterface &$query) {
  // Get the adapter derivative.
  // Get the plugin manager.
  /** @var \Drupal\facetapi\Adapter\AdapterPluginManagerInterface $plugin_manager */
  $plugin_manager = \Drupal::service('plugin.manager.facetapi.adapter');

  // Get the searcher id.
  // This is the id of the view.
  $search_id = $query->getOption('search id');

  $plugin_id = 'search_api_views';

  $adapter = $plugin_manager->getMyOwnChangeLaterInstance($plugin_id, $search_id);

  // Add the active filters.
  $adapter->alterQuery($query);

}

/**
 * Implementation of hook_facetapi_facet_info().
 *
 * @return array
 */
function facetapi_facetapi_facet_info() {
  $get_facets = \Drupal::service('search_api_facets.get_facets');
  return $get_facets->getFacets();
}
