<?php

/**
 * @file
 * Contains facet_api.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function facet_api_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the facet_api module.
    case 'help.page.facet_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Facetapi test') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function facet_api_theme()
{
  $theme = [];

  return $theme;
}
