<?php
/**
 * Hooks
 */
use Drupal\search_api\Query\QueryInterface;
use Drupal\Component\Plugin\PluginBase;

/**
 * Implementation of hook_facetapi_searcher_info.
 *
 * @return array
 */
function search_api_facets_facetapi_searcher_info() {
  return array(
    'search' => array(
      'label'                   => t('Search'),
      'adapter'                 => 'search',
//      'url processor'           => 'standard',
      'types'                   => array('node'),
      'path'                    => 'admin/config/search/settings',
    ),
  );
}


/**
 * Implementation of hook_search_api_query_alter.
 *
 * @param \Drupal\search_api\Query\QueryInterface $query
 */
function search_api_facets_search_api_query_alter(QueryInterface &$query) {
  // Get the adapter derivative.
  // Get the plugin manager.
  $plugin_manager = \Drupal::service('plugin.manager.facetapi.adapter');
  // Get the index id.
  $index = $query->getIndex();
  $index_id = $index->getOriginalId();
  $config = array('index' => $index);

  $base_plugin_id = 'search_api';

  $plugin_id = $base_plugin_id . PluginBase::DERIVATIVE_SEPARATOR . $index_id;

  $adapter = $plugin_manager->createInstance($plugin_id, $config);

}